version: '3.8'

services:
  sksoluciones:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sksoluciones-nuxt
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_PRIVATE_DB_USER=${NUXT_PRIVATE_DB_USER}
      - NUXT_PRIVATE_DB_HOST=${NUXT_PRIVATE_DB_HOST}
      - NUXT_PRIVATE_DB_NAME=${NUXT_PRIVATE_DB_NAME}
      - NUXT_PRIVATE_DB_PASSWORD=${NUXT_PRIVATE_DB_PASSWORD}
      - NUXT_PRIVATE_DB_PORT=${NUXT_PRIVATE_DB_PORT}
    volumes:
      - nuxt-data:/app/storage
    networks:
      - sksoluciones-network
    restart: unless-stopped

networks:
  sksoluciones-network:
    external: true

volumes:
  nuxt-data: